<?php

/* @var $this Mage_Core_Block_Template */

require_once 'lib/giveit/sdk.php';

define('GIVEIT_PUBLIC_KEY',  Mage::getStoreConfig('synocom_giveit/account_settings/public_key'));
define('GIVEIT_DATA_KEY',  Mage::getStoreConfig('synocom_giveit/account_settings/data_key'));
define('GIVEIT_PRIVATE_KEY',  Mage::getStoreConfig('synocom_giveit/account_settings/private_key'));

$giveIt = new \GiveIt\SDK;
$giveIt->debug = true;
$giveIt->setEnvironment('sandbox');


$product = $this->getLayout()->getBlock('product.info')->getProduct();

$code       = $product->getSku();
$name       = $product->getName();
$price      = (int) round($price * 100, 0);
$image      = $product->getImage();
$product    = new \GiveIt\SDK\Product();

$product->setProductDetails($code, $price, $name, $image);

$delivery = $product->addDeliveryOption('delivery','Delivery Option');
$product->addChoice($delivery,'europe','Europe',900);
$product->addChoice($delivery,'usa','United States',499);

$result = $product->validate();


if ($result == true){
    $htmlFromProduct    = $product->getButtonHTML();
    echo $htmlFromProduct;
}
else {
    $errorsHTML = $product->getErrorsHTML();
    echo $errorsHTML;
}


$giveIt->outputButtonJS();
